SET DEFINE OFF;
-- ============================================================
-- SNEAKER SHOP - ORACLE DATABASE 25 BẢNG
-- ============================================================

-- 0. XÓA CŨ
BEGIN FOR r IN (SELECT table_name FROM user_tables) LOOP EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE'; END LOOP; END;
/
BEGIN FOR r IN (SELECT sequence_name FROM user_sequences) LOOP EXECUTE IMMEDIATE 'DROP SEQUENCE ' || r.sequence_name; END LOOP; END;
/

-- 1. SEQUENCES
CREATE SEQUENCE SEQ_NGUOIDUNG START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DANHMUC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THUONGHIEU START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SANPHAM START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DONHANG START WITH 1001 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHITIET START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THANHTOAN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DANHGIA START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_GIOHANG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CTGH START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KHUYENMAI START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SPKM START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VOUCHER START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VND START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TINTUC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BLTT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LIENHE START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NCC START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CTPN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LSTK START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SPYT START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TB START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DCGH START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_KICHCO START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- 2. TẠO 25 BẢNG
-- ============================================================

-- B1. NGUOIDUNG
CREATE TABLE NGUOIDUNG (
    Manguoidung VARCHAR2(10) PRIMARY KEY,
    TenND VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    MatKhau VARCHAR2(255) NOT NULL,
    SoDienThoai VARCHAR2(20),
    DiaChi VARCHAR2(255),
    VaiTro VARCHAR2(20) DEFAULT 'KHACHHANG',
    TrangThai VARCHAR2(20) DEFAULT 'HOATDONG',
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- B2. DANHMUC
CREATE TABLE DANHMUC (
    Madanhmuc VARCHAR2(10) PRIMARY KEY,
    TenDM VARCHAR2(100) NOT NULL,
    MoTa VARCHAR2(500),
    TrangThai VARCHAR2(20) DEFAULT 'HOATDONG'
);

-- B3. THUONGHIEU
CREATE TABLE THUONGHIEU (
    Mathuonghieu VARCHAR2(10) PRIMARY KEY,
    TenTH VARCHAR2(100) NOT NULL,
    LogoUrl VARCHAR2(500),
    QuocGia VARCHAR2(50),
    MoTa CLOB,
    TrangThai VARCHAR2(20) DEFAULT 'HOATDONG'
);

-- B4. SANPHAM
CREATE TABLE SANPHAM (
    Masanpham VARCHAR2(10) PRIMARY KEY,
    TenSP VARCHAR2(200) NOT NULL,
    Madanhmuc VARCHAR2(10),
    Mathuonghieu VARCHAR2(10),
    Gia NUMBER(19,4) NOT NULL,
    GiaGoc NUMBER(19,4),
    HinhAnh VARCHAR2(500),
    SoLuong NUMBER DEFAULT 0,
    TrangThai VARCHAR2(20) DEFAULT 'CONHANG',
    MoTa CLOB,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SP_DM FOREIGN KEY (Madanhmuc) REFERENCES DANHMUC(Madanhmuc),
    CONSTRAINT FK_SP_TH FOREIGN KEY (Mathuonghieu) REFERENCES THUONGHIEU(Mathuonghieu)
);

-- B5. KICHCO_SANPHAM
CREATE TABLE KICHCO_SANPHAM (
    MaKichCo VARCHAR2(10) PRIMARY KEY,
    Masanpham VARCHAR2(10),
    TenKichCo VARCHAR2(20) NOT NULL,
    SoLuong NUMBER DEFAULT 0,
    CONSTRAINT FK_KC_SP FOREIGN KEY (Masanpham) REFERENCES SANPHAM(Masanpham)
);

-- B6. DONHANG
CREATE TABLE DONHANG (
    Madonhang VARCHAR2(10) PRIMARY KEY,
    Manguoidung VARCHAR2(10),
    TenNguoiNhan VARCHAR2(100) NOT NULL,
    SdtNguoiNhan VARCHAR2(20),
    DiaChiGiao VARCHAR2(255) NOT NULL,
    ThanhPho VARCHAR2(100),
    TongTien NUMBER(19,4) DEFAULT 0,
    PhiShip NUMBER(19,4) DEFAULT 0,
    Thue NUMBER(19,4) DEFAULT 0,
    TongCong NUMBER(19,4) DEFAULT 0,
    TrangThai VARCHAR2(20) DEFAULT 'CHOXULY',
    NgayDat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DH_ND FOREIGN KEY (Manguoidung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B7. CHITIETDONHANG
CREATE TABLE CHITIETDONHANG (
    Machitiet VARCHAR2(10) PRIMARY KEY,
    Madonhang VARCHAR2(10),
    Masanpham VARCHAR2(10),
    KichCo VARCHAR2(10) DEFAULT 'US 9',
    SoLuong NUMBER NOT NULL,
    DonGia NUMBER(19,4) NOT NULL,
    ThanhTien NUMBER(19,4),
    CONSTRAINT FK_CT_DH FOREIGN KEY (Madonhang) REFERENCES DONHANG(Madonhang),
    CONSTRAINT FK_CT_SP FOREIGN KEY (Masanpham) REFERENCES SANPHAM(Masanpham)
);

-- B8. THANHTOAN
CREATE TABLE THANHTOAN (
    Mathanhtoan VARCHAR2(10) PRIMARY KEY,
    Madonhang VARCHAR2(10),
    PhuongThuc VARCHAR2(50) NOT NULL,
    SoTien NUMBER(19,4) NOT NULL,
    TrangThai VARCHAR2(20) DEFAULT 'CHOTHANHTOAN',
    MaGiaoDich VARCHAR2(100),
    NgayThanhToan TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TT_DH FOREIGN KEY (Madonhang) REFERENCES DONHANG(Madonhang)
);

-- B9. DANHGIA
CREATE TABLE DANHGIA (
    Madanhgia VARCHAR2(10) PRIMARY KEY,
    Masanpham VARCHAR2(10),
    Manguoidung VARCHAR2(10),
    SoSao NUMBER(1) CHECK (SoSao BETWEEN 1 AND 5),
    BinhLuan CLOB,
    NgayDanhGia TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_DG_SP FOREIGN KEY (Masanpham) REFERENCES SANPHAM(Masanpham),
    CONSTRAINT FK_DG_ND FOREIGN KEY (Manguoidung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B10. GIOHANG
CREATE TABLE GIOHANG (
    MaGioHang VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10) UNIQUE,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_GH_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B11. CHITIETGIOHANG
CREATE TABLE CHITIETGIOHANG (
    MaCTGH VARCHAR2(10) PRIMARY KEY,
    MaGioHang VARCHAR2(10),
    MaSanPham VARCHAR2(10),
    KichCo VARCHAR2(10),
    SoLuong NUMBER DEFAULT 1,
    CONSTRAINT FK_CTGH_GH FOREIGN KEY (MaGioHang) REFERENCES GIOHANG(MaGioHang),
    CONSTRAINT FK_CTGH_SP FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(Masanpham)
);

-- B12. KHUYENMAI
CREATE TABLE KHUYENMAI (
    MaKhuyenMai VARCHAR2(10) PRIMARY KEY,
    TenKM VARCHAR2(200) NOT NULL,
    PhanTramGiam NUMBER(5,2),
    NgayBatDau TIMESTAMP,
    NgayKetThuc TIMESTAMP,
    TrangThai VARCHAR2(20) DEFAULT 'DANGCHAY'
);

-- B13. SANPHAM_KHUYENMAI
CREATE TABLE SANPHAM_KHUYENMAI (
    MaSPKM VARCHAR2(10) PRIMARY KEY,
    MaKhuyenMai VARCHAR2(10),
    MaSanPham VARCHAR2(10),
    CONSTRAINT FK_SPKM_KM FOREIGN KEY (MaKhuyenMai) REFERENCES KHUYENMAI(MaKhuyenMai),
    CONSTRAINT FK_SPKM_SP FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(Masanpham)
);

-- B14. VOUCHER
CREATE TABLE VOUCHER (
    MaVoucher VARCHAR2(20) PRIMARY KEY,
    PhanTramGiam NUMBER(5,2),
    SoTienGiam NUMBER(19,4),
    DonHangToiThieu NUMBER(19,4),
    SoLuong NUMBER DEFAULT 100,
    NgayHetHan TIMESTAMP
);

-- B15. VOUCHER_NGUOIDUNG
CREATE TABLE VOUCHER_NGUOIDUNG (
    MaVND VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10),
    MaVoucher VARCHAR2(20),
    TrangThai VARCHAR2(20) DEFAULT 'CHUA_SU_DUNG',
    CONSTRAINT FK_VND_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung),
    CONSTRAINT FK_VND_V FOREIGN KEY (MaVoucher) REFERENCES VOUCHER(MaVoucher)
);

-- B16. TINTUC
CREATE TABLE TINTUC (
    MaTinTuc VARCHAR2(10) PRIMARY KEY,
    TieuDe VARCHAR2(500) NOT NULL,
    NoiDung CLOB NOT NULL,
    HinhAnh VARCHAR2(500),
    NgayDang TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- B17. BINHLUAN_TINTUC
CREATE TABLE BINHLUAN_TINTUC (
    MaBLTT VARCHAR2(10) PRIMARY KEY,
    MaTinTuc VARCHAR2(10),
    MaNguoiDung VARCHAR2(10),
    BinhLuan CLOB NOT NULL,
    NgayBL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BLTT_TT FOREIGN KEY (MaTinTuc) REFERENCES TINTUC(MaTinTuc),
    CONSTRAINT FK_BLTT_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B18. LIENHE
CREATE TABLE LIENHE (
    MaLienHe VARCHAR2(10) PRIMARY KEY,
    TenNguoiLienHe VARCHAR2(100),
    Email VARCHAR2(100),
    TieuDe VARCHAR2(200),
    NoiDung CLOB,
    TrangThai VARCHAR2(20) DEFAULT 'CHUA_XU_LY'
);

-- B19. NHACUNGCAP
CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR2(10) PRIMARY KEY,
    TenNCC VARCHAR2(200) NOT NULL,
    SoDienThoai VARCHAR2(20),
    DiaChi VARCHAR2(500),
    TrangThai VARCHAR2(20) DEFAULT 'HOATDONG'
);

-- B20. PHIEUNHAP
CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR2(10) PRIMARY KEY,
    MaNCC VARCHAR2(10),
    NgayNhap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TongTien NUMBER(19,4) DEFAULT 0,
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);

-- B21. CHITIETPHIEUNHAP
CREATE TABLE CHITIETPHIEUNHAP (
    MaCTPN VARCHAR2(10) PRIMARY KEY,
    MaPN VARCHAR2(10),
    MaSanPham VARCHAR2(10),
    SoLuong NUMBER NOT NULL,
    DonGiaNhap NUMBER(19,4) NOT NULL,
    ThanhTien NUMBER(19,4),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN),
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(Masanpham)
);

-- B22. LICHSUTIMKIEM
CREATE TABLE LICHSUTIMKIEM (
    MaLSTK VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10),
    TuKhoa VARCHAR2(200),
    NgayTimKiem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LSTK_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B23. SANPHAM_YEUTHICH
CREATE TABLE SANPHAM_YEUTHICH (
    MaSPYT VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10),
    MaSanPham VARCHAR2(10),
    NgayThem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_SPYT_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung),
    CONSTRAINT FK_SPYT_SP FOREIGN KEY (MaSanPham) REFERENCES SANPHAM(Masanpham)
);

-- B24. THONGBAO
CREATE TABLE THONGBAO (
    MaTB VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10),
    TieuDe VARCHAR2(200),
    NoiDung CLOB,
    DaDoc NUMBER(1) DEFAULT 0,
    NgayTB TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TB_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung)
);

-- B25. DIACHI_GIAOHANG
CREATE TABLE DIACHI_GIAOHANG (
    MaDCGH VARCHAR2(10) PRIMARY KEY,
    MaNguoiDung VARCHAR2(10),
    TenNguoiNhan VARCHAR2(100),
    SdtNguoiNhan VARCHAR2(20),
    DiaChiChiTiet VARCHAR2(500),
    MacDinh NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_DCGH_ND FOREIGN KEY (MaNguoiDung) REFERENCES NGUOIDUNG(Manguoidung)
);
