DELETE FROM KICHCO_SANPHAM;
DELETE FROM CHITIETGIOHANG;
DELETE FROM CHITIETDONHANG;
DELETE FROM DANHGIA;
DELETE FROM SANPHAM_KHUYENMAI;
DELETE FROM CHITIETPHIEUNHAP;
DELETE FROM SANPHAM_YEUTHICH;
DELETE FROM SANPHAM;
COMMIT;
@database/scraped_goat_all_seed.sql
EXIT;
