SET DEFINE OFF;
-- ============================================================
-- TRIGGERS TỰ ĐỘNG TẠO ID
-- ============================================================
CREATE OR REPLACE TRIGGER TRG_NGUOIDUNG_ID BEFORE INSERT ON NGUOIDUNG FOR EACH ROW
BEGIN IF :NEW.Manguoidung IS NULL THEN :NEW.Manguoidung := 'ND' || SEQ_NGUOIDUNG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DANHMUC_ID BEFORE INSERT ON DANHMUC FOR EACH ROW
BEGIN IF :NEW.Madanhmuc IS NULL THEN :NEW.Madanhmuc := 'DM' || SEQ_DANHMUC.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_THUONGHIEU_ID BEFORE INSERT ON THUONGHIEU FOR EACH ROW
BEGIN IF :NEW.Mathuonghieu IS NULL THEN :NEW.Mathuonghieu := 'TH' || SEQ_THUONGHIEU.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_SANPHAM_ID BEFORE INSERT ON SANPHAM FOR EACH ROW
BEGIN IF :NEW.Masanpham IS NULL THEN :NEW.Masanpham := 'SP' || SEQ_SANPHAM.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DONHANG_ID BEFORE INSERT ON DONHANG FOR EACH ROW
BEGIN IF :NEW.Madonhang IS NULL THEN :NEW.Madonhang := 'DH' || SEQ_DONHANG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CHITIET_ID BEFORE INSERT ON CHITIETDONHANG FOR EACH ROW
BEGIN IF :NEW.Machitiet IS NULL THEN :NEW.Machitiet := 'CT' || SEQ_CHITIET.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_THANHTOAN_ID BEFORE INSERT ON THANHTOAN FOR EACH ROW
BEGIN IF :NEW.Mathanhtoan IS NULL THEN :NEW.Mathanhtoan := 'TT' || SEQ_THANHTOAN.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DANHGIA_ID BEFORE INSERT ON DANHGIA FOR EACH ROW
BEGIN IF :NEW.Madanhgia IS NULL THEN :NEW.Madanhgia := 'DG' || SEQ_DANHGIA.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_GIOHANG_ID BEFORE INSERT ON GIOHANG FOR EACH ROW
BEGIN IF :NEW.MaGioHang IS NULL THEN :NEW.MaGioHang := 'GH' || SEQ_GIOHANG.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CTGH_ID BEFORE INSERT ON CHITIETGIOHANG FOR EACH ROW
BEGIN IF :NEW.MaCTGH IS NULL THEN :NEW.MaCTGH := 'CG' || SEQ_CTGH.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_KM_ID BEFORE INSERT ON KHUYENMAI FOR EACH ROW
BEGIN IF :NEW.MaKhuyenMai IS NULL THEN :NEW.MaKhuyenMai := 'KM' || SEQ_KHUYENMAI.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_SPKM_ID BEFORE INSERT ON SANPHAM_KHUYENMAI FOR EACH ROW
BEGIN IF :NEW.MaSPKM IS NULL THEN :NEW.MaSPKM := 'SK' || SEQ_SPKM.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_VND_ID BEFORE INSERT ON VOUCHER_NGUOIDUNG FOR EACH ROW
BEGIN IF :NEW.MaVND IS NULL THEN :NEW.MaVND := 'VN' || SEQ_VND.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_TT_ID BEFORE INSERT ON TINTUC FOR EACH ROW
BEGIN IF :NEW.MaTinTuc IS NULL THEN :NEW.MaTinTuc := 'TT' || SEQ_TINTUC.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_BLTT_ID BEFORE INSERT ON BINHLUAN_TINTUC FOR EACH ROW
BEGIN IF :NEW.MaBLTT IS NULL THEN :NEW.MaBLTT := 'BL' || SEQ_BLTT.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_LH_ID BEFORE INSERT ON LIENHE FOR EACH ROW
BEGIN IF :NEW.MaLienHe IS NULL THEN :NEW.MaLienHe := 'LH' || SEQ_LIENHE.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_NCC_ID BEFORE INSERT ON NHACUNGCAP FOR EACH ROW
BEGIN IF :NEW.MaNCC IS NULL THEN :NEW.MaNCC := 'NC' || SEQ_NCC.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_PN_ID BEFORE INSERT ON PHIEUNHAP FOR EACH ROW
BEGIN IF :NEW.MaPN IS NULL THEN :NEW.MaPN := 'PN' || SEQ_PN.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_CTPN_ID BEFORE INSERT ON CHITIETPHIEUNHAP FOR EACH ROW
BEGIN IF :NEW.MaCTPN IS NULL THEN :NEW.MaCTPN := 'CP' || SEQ_CTPN.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_LSTK_ID BEFORE INSERT ON LICHSUTIMKIEM FOR EACH ROW
BEGIN IF :NEW.MaLSTK IS NULL THEN :NEW.MaLSTK := 'LS' || SEQ_LSTK.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_SPYT_ID BEFORE INSERT ON SANPHAM_YEUTHICH FOR EACH ROW
BEGIN IF :NEW.MaSPYT IS NULL THEN :NEW.MaSPYT := 'YT' || SEQ_SPYT.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_TB_ID BEFORE INSERT ON THONGBAO FOR EACH ROW
BEGIN IF :NEW.MaTB IS NULL THEN :NEW.MaTB := 'TB' || SEQ_TB.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_DCGH_ID BEFORE INSERT ON DIACHI_GIAOHANG FOR EACH ROW
BEGIN IF :NEW.MaDCGH IS NULL THEN :NEW.MaDCGH := 'DC' || SEQ_DCGH.NEXTVAL; END IF; END;
/
CREATE OR REPLACE TRIGGER TRG_KC_ID BEFORE INSERT ON KICHCO_SANPHAM FOR EACH ROW
BEGIN IF :NEW.MaKichCo IS NULL THEN :NEW.MaKichCo := 'KC' || SEQ_KICHCO.NEXTVAL; END IF; END;
/

-- ============================================================
-- TRIGGERS NGHIỆP VỤ
-- ============================================================

-- T1: Tự động tính ThanhTien
CREATE OR REPLACE TRIGGER TRG_TINH_THANHTIEN
BEFORE INSERT OR UPDATE OF SoLuong, DonGia ON CHITIETDONHANG FOR EACH ROW
BEGIN :NEW.ThanhTien := :NEW.SoLuong * :NEW.DonGia; END;
/

-- T2: Trừ tồn kho khi đặt hàng
CREATE OR REPLACE TRIGGER TRG_TRU_TONKHO
AFTER INSERT ON CHITIETDONHANG FOR EACH ROW
BEGIN
    UPDATE SANPHAM SET SoLuong = SoLuong - :NEW.SoLuong, NgayCapNhat = CURRENT_TIMESTAMP WHERE Masanpham = :NEW.Masanpham;
END;
/

-- T3: Cộng lại tồn kho khi hủy
CREATE OR REPLACE TRIGGER TRG_CONG_LAI_TONKHO
AFTER DELETE ON CHITIETDONHANG FOR EACH ROW
BEGIN
    UPDATE SANPHAM SET SoLuong = SoLuong + :OLD.SoLuong, NgayCapNhat = CURRENT_TIMESTAMP WHERE Masanpham = :OLD.Masanpham;
END;
/

-- T4: Cập nhật trạng thái hết hàng/còn hàng
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_TRANGTHAI_SP
AFTER UPDATE OF SoLuong ON SANPHAM FOR EACH ROW
BEGIN
    IF :NEW.SoLuong <= 0 AND :OLD.TrangThai != 'HETHANG' THEN
        UPDATE SANPHAM SET TrangThai = 'HETHANG' WHERE Masanpham = :NEW.Masanpham;
    ELSIF :NEW.SoLuong > 0 AND :OLD.TrangThai = 'HETHANG' THEN
        UPDATE SANPHAM SET TrangThai = 'CONHANG' WHERE Masanpham = :NEW.Masanpham;
    END IF;
END;
/

-- T5: Tự động cập nhật tổng tiền đơn hàng
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_TONGTIEN_DH
AFTER INSERT OR DELETE ON CHITIETDONHANG FOR EACH ROW
DECLARE v_Delta NUMBER(19,4);
BEGIN
    IF INSERTING THEN
        v_Delta := :NEW.ThanhTien;
        UPDATE DONHANG SET TongTien = NVL(TongTien,0) + v_Delta, Thue = (NVL(TongTien,0) + v_Delta) * 0.08, TongCong = (NVL(TongTien,0) + v_Delta) * 1.08, NgayCapNhat = CURRENT_TIMESTAMP WHERE Madonhang = :NEW.Madonhang;
    ELSIF DELETING THEN
        v_Delta := :OLD.ThanhTien;
        UPDATE DONHANG SET TongTien = GREATEST(NVL(TongTien,0) - v_Delta, 0), Thue = GREATEST(NVL(TongTien,0) - v_Delta, 0) * 0.08, TongCong = GREATEST(NVL(TongTien,0) - v_Delta, 0) * 1.08, NgayCapNhat = CURRENT_TIMESTAMP WHERE Madonhang = :OLD.Madonhang;
    END IF;
END;
/

-- T6: Tính ThanhTien cho phiếu nhập
CREATE OR REPLACE TRIGGER TRG_TINH_THANHTIEN_PN
BEFORE INSERT OR UPDATE OF SoLuong, DonGiaNhap ON CHITIETPHIEUNHAP FOR EACH ROW
BEGIN :NEW.ThanhTien := :NEW.SoLuong * :NEW.DonGiaNhap; END;
/

-- T7: Cập nhật tổng tiền phiếu nhập + cộng tồn kho khi nhập hàng
CREATE OR REPLACE TRIGGER TRG_CAPNHAT_PN_TONKHO
AFTER INSERT ON CHITIETPHIEUNHAP FOR EACH ROW
BEGIN
    UPDATE PHIEUNHAP SET TongTien = TongTien + :NEW.ThanhTien WHERE MaPN = :NEW.MaPN;
    UPDATE SANPHAM SET SoLuong = SoLuong + :NEW.SoLuong WHERE Masanpham = :NEW.MaSanPham;
END;
/

-- T8: Tự động gửi thông báo khi đặt hàng thành công
CREATE OR REPLACE TRIGGER TRG_THONGBAO_DATHANG
AFTER INSERT ON DONHANG FOR EACH ROW
BEGIN
    INSERT INTO THONGBAO (MaNguoiDung, TieuDe, NoiDung)
    VALUES (:NEW.Manguoidung, 'Đặt hàng thành công', 'Đơn hàng ' || :NEW.Madonhang || ' đã được tạo.');
END;
/

-- ============================================================
-- STORED PROCEDURES
-- ============================================================

-- P1: Thêm sản phẩm mới
CREATE OR REPLACE PROCEDURE INSERT_SANPHAM(
    p_TenSP IN VARCHAR2, p_Madanhmuc IN VARCHAR2, p_Mathuonghieu IN VARCHAR2,
    p_Gia IN NUMBER, p_GiaGoc IN NUMBER, p_HinhAnh IN VARCHAR2, p_SoLuong IN NUMBER, p_MoTa IN CLOB
) IS
BEGIN
    INSERT INTO SANPHAM (TenSP, Madanhmuc, Mathuonghieu, Gia, GiaGoc, HinhAnh, SoLuong, MoTa)
    VALUES (p_TenSP, p_Madanhmuc, p_Mathuonghieu, p_Gia, p_GiaGoc, p_HinhAnh, p_SoLuong, p_MoTa);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P2: Cập nhật người dùng
CREATE OR REPLACE PROCEDURE UPDATE_NGUOIDUNG(
    p_Manguoidung IN VARCHAR2, p_TenND IN VARCHAR2, p_SoDienThoai IN VARCHAR2, p_DiaChi IN VARCHAR2
) IS
BEGIN
    UPDATE NGUOIDUNG SET TenND = p_TenND, SoDienThoai = p_SoDienThoai, DiaChi = p_DiaChi, NgayCapNhat = CURRENT_TIMESTAMP
    WHERE Manguoidung = p_Manguoidung;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P3: Đổi mật khẩu
CREATE OR REPLACE PROCEDURE DOI_MAT_KHAU(
    p_Manguoidung IN VARCHAR2, p_MatKhauCu IN VARCHAR2, p_MatKhauMoi IN VARCHAR2
) IS v_Cur VARCHAR2(255);
BEGIN
    SELECT MatKhau INTO v_Cur FROM NGUOIDUNG WHERE Manguoidung = p_Manguoidung;
    IF v_Cur != p_MatKhauCu THEN DBMS_OUTPUT.PUT_LINE('Mat khau cu khong dung!'); RETURN; END IF;
    UPDATE NGUOIDUNG SET MatKhau = p_MatKhauMoi, NgayCapNhat = CURRENT_TIMESTAMP WHERE Manguoidung = p_Manguoidung;
    COMMIT;
EXCEPTION WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('Khong tim thay!');
    WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P4: Đặt hàng (kiểm tra tồn kho)
CREATE OR REPLACE PROCEDURE DAT_HANG(
    p_Manguoidung IN VARCHAR2, p_TenNguoiNhan IN VARCHAR2, p_SdtNguoiNhan IN VARCHAR2,
    p_DiaChiGiao IN VARCHAR2, p_ThanhPho IN VARCHAR2, p_Masanpham IN VARCHAR2, p_KichCo IN VARCHAR2, p_SoLuong IN NUMBER
) IS v_Madonhang VARCHAR2(10); v_SLTon NUMBER; v_Gia NUMBER(19,4); v_TT VARCHAR2(20);
BEGIN
    SELECT SoLuong, Gia, TrangThai INTO v_SLTon, v_Gia, v_TT FROM SANPHAM WHERE Masanpham = p_Masanpham;
    IF v_TT = 'HETHANG' OR v_SLTon < p_SoLuong THEN DBMS_OUTPUT.PUT_LINE('Khong du ton kho!'); RETURN; END IF;
    INSERT INTO DONHANG (Manguoidung, TenNguoiNhan, SdtNguoiNhan, DiaChiGiao, ThanhPho) VALUES (p_Manguoidung, p_TenNguoiNhan, p_SdtNguoiNhan, p_DiaChiGiao, p_ThanhPho);
    SELECT Madonhang INTO v_Madonhang FROM DONHANG WHERE Manguoidung = p_Manguoidung ORDER BY NgayDat DESC FETCH FIRST 1 ROW ONLY;
    INSERT INTO CHITIETDONHANG (Madonhang, Masanpham, KichCo, SoLuong, DonGia) VALUES (v_Madonhang, p_Masanpham, p_KichCo, p_SoLuong, v_Gia);
    COMMIT;
EXCEPTION WHEN NO_DATA_FOUND THEN DBMS_OUTPUT.PUT_LINE('Khong tim thay SP!');
    WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P5: Hủy đơn hàng
CREATE OR REPLACE PROCEDURE HUY_DONHANG(p_Madonhang IN VARCHAR2) IS
BEGIN
    UPDATE DONHANG SET TrangThai = 'DAHUY', NgayCapNhat = CURRENT_TIMESTAMP WHERE Madonhang = p_Madonhang;
    DELETE FROM CHITIETDONHANG WHERE Madonhang = p_Madonhang;
    DELETE FROM THANHTOAN WHERE Madonhang = p_Madonhang;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P6: Thanh toán đơn hàng
CREATE OR REPLACE PROCEDURE THANH_TOAN_DONHANG(p_Madonhang IN VARCHAR2, p_PhuongThuc IN VARCHAR2) IS
    v_TongCong NUMBER(19,4);
BEGIN
    SELECT TongCong INTO v_TongCong FROM DONHANG WHERE Madonhang = p_Madonhang;
    INSERT INTO THANHTOAN (Madonhang, PhuongThuc, SoTien, TrangThai, MaGiaoDich)
    VALUES (p_Madonhang, p_PhuongThuc, v_TongCong, 'DATHANHTOAN', 'TXN' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS'));
    UPDATE DONHANG SET TrangThai = 'DANGXULY', NgayCapNhat = CURRENT_TIMESTAMP WHERE Madonhang = p_Madonhang;
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P7: Thêm đánh giá
CREATE OR REPLACE PROCEDURE THEM_DANHGIA(p_Masanpham IN VARCHAR2, p_Manguoidung IN VARCHAR2, p_SoSao IN NUMBER, p_BinhLuan IN CLOB) IS
BEGIN
    INSERT INTO DANHGIA (Masanpham, Manguoidung, SoSao, BinhLuan) VALUES (p_Masanpham, p_Manguoidung, p_SoSao, p_BinhLuan);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P8: Thêm vào giỏ hàng
CREATE OR REPLACE PROCEDURE THEM_VAO_GIOHANG(p_MaNguoiDung IN VARCHAR2, p_MaSanPham IN VARCHAR2, p_KichCo IN VARCHAR2, p_SoLuong IN NUMBER) IS
    v_MaGH VARCHAR2(10); v_Count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_Count FROM GIOHANG WHERE MaNguoiDung = p_MaNguoiDung;
    IF v_Count = 0 THEN
        INSERT INTO GIOHANG(MaNguoiDung) VALUES(p_MaNguoiDung) RETURNING MaGioHang INTO v_MaGH;
    ELSE SELECT MaGioHang INTO v_MaGH FROM GIOHANG WHERE MaNguoiDung = p_MaNguoiDung;
    END IF;
    INSERT INTO CHITIETGIOHANG(MaGioHang, MaSanPham, KichCo, SoLuong) VALUES (v_MaGH, p_MaSanPham, p_KichCo, p_SoLuong);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/

-- P9: Báo cáo doanh thu theo tháng
CREATE OR REPLACE PROCEDURE BAO_CAO_DOANH_THU(p_Thang IN NUMBER, p_Nam IN NUMBER) IS
    v_TongDT NUMBER; v_SoDon NUMBER;
BEGIN
    SELECT NVL(SUM(TongCong),0), COUNT(*) INTO v_TongDT, v_SoDon FROM DONHANG
    WHERE EXTRACT(MONTH FROM NgayDat) = p_Thang AND EXTRACT(YEAR FROM NgayDat) = p_Nam AND TrangThai != 'DAHUY';
    DBMS_OUTPUT.PUT_LINE('Thang ' || p_Thang || '/' || p_Nam || ': ' || v_SoDon || ' don, Doanh thu: ' || v_TongDT);
END;
/

-- P10: Nhập hàng từ nhà cung cấp
CREATE OR REPLACE PROCEDURE NHAP_HANG(p_MaNCC IN VARCHAR2, p_MaSanPham IN VARCHAR2, p_SoLuong IN NUMBER, p_DonGiaNhap IN NUMBER) IS
    v_MaPN VARCHAR2(10);
BEGIN
    INSERT INTO PHIEUNHAP(MaNCC) VALUES(p_MaNCC) RETURNING MaPN INTO v_MaPN;
    INSERT INTO CHITIETPHIEUNHAP(MaPN, MaSanPham, SoLuong, DonGiaNhap) VALUES(v_MaPN, p_MaSanPham, p_SoLuong, p_DonGiaNhap);
    COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
END;
/
